# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e8d6692a51b2dbd63dcdb505a75fc0ad7045ab1e3d868bc6bb4b25a330df12f9151e6f38340c9ad8666a570aab2e48c38dc2c5f9120ba622f0f913e3849b30e

test:
  secret_key_base: 77431a4459af907c0faf9c4455121f36dc105b50e1e518fbf29f09d25271e1ba5e102a67d1f9ff280e78ca7b0dda700aed8b1160c9fbf2d6d82f4404875a5773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
